'use client';
import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext({
  language: 'ar',
  setLanguage: () => {},
  t: (key) => key,
});

const translations = {
  ar: {
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    theme: 'المظهر',
    language: 'اللغة',
    logout: 'تسجيل الخروج',
    edit: 'تعديل',
    name: 'الاسم',
    bio: 'نبذة شخصية',
    location: 'الموقع',
    save: 'حفظ التغييرات',
    dark: 'ليلي',
    light: 'نهاري',
    arabic: 'العربية',
    english: 'English',
    my_account: 'حسابي',
    home: 'الرئيسية',
    shop: 'المتجر',
    about: 'من نحن',
    contact: 'تواصل معنا',
    become_artisan: 'كن حرفياً',
    store_setup: 'إعداد المتجر',
    store_name: 'اسم المتجر',
    store_description: 'وصف المتجر',
    submit: 'إرسال',
    privacy_policy: 'سياسة الخصوصية',
    login: 'تسجيل الدخول',
    all_products: 'كل المنتجات',
    latest_products: 'أحدث المنتجات',
    best_selling: 'الأكثر مبيعاً',
    specifications: 'مميزاتنا',
    newsletter_title: 'انضم إلى نشرتنا الإخبارية',
    newsletter_desc: 'احصل على آخر التحديثات والعروض الحصرية مباشرة في بريدك الوارد.',
    get_updates: 'احصل على التحديثات',
    view_more: 'عرض المزيد',
    showing_products: 'عرض {count} من {total} منتجات',
    wishlist: 'قائمة الأمنيات',
    search_placeholder: 'ابحث عن منتجات...',
    search_btn: 'بحث',
    my_orders: 'طلباتي',
    hero_badge: 'جديد',
    hero_badge_text: 'دعم الحرفيين المحليين - كل قطعة فريدة',
    hero_title: 'منتجات حرفية أصيلة. بلمسة جزائرية.',
    hero_desc: 'اكتشف روائع الحرف اليدوية الجزائرية - من الفخار إلى المنسوجات، كل منتج يحكي قصة تراثنا العريق',
    price_starts: 'تبدأ الأسعار من',
    explore_products: 'استكشف المنتجات',
    traditional_crafts: 'حرف تقليدية',
    natural_products: 'منتجات طبيعية',
    discover_more: 'اكتشف المزيد',
    browse_now: 'تصفح الآن',
    enter_email: 'أدخل بريدك الإلكتروني',
    spec_shipping_title: 'توصيل مجاني',
    spec_shipping_desc: 'توصيل سريع ومجاني لجميع الطلبات داخل الوطن',
    spec_returns_title: 'إرجاع سهل خلال 7 أيام',
    spec_returns_desc: 'غيرت رأيك؟ لا مشكلة. يمكنك إرجاع المنتج خلال 7 أيام',
    spec_support_title: 'دعم 24/7',
    spec_support_desc: 'نحن هنا لمساعدتك في أي وقت مع خدمة عملاء احترافية',
    specifications_desc: 'نحن نقدم خدمة رفيعة المستوى وراحة تامة لضمان أن تكون تجربة التسوق الخاصة بك سلسة وآمنة وخالية تماماً من المتاعب.',
    categories_title: 'الأقسام',
    useful_links: 'روابط مفيدة',
    contact_us: 'تواصل معنا',
    footer_desc: 'Manuva - منصتك الأولى لاكتشاف المنتجات الحرفية الجزائرية الأصيلة. من الفخار إلى المنسوجات، كل قطعة تحكي قصة تراثنا العريق وتدعم حرفيينا المحليين.',
    copyright: 'حقوق النشر 2026 © Manuva. جميع الحقوق محفوظة.',
    made_with_love: 'صنع بحب في الجزائر 🇩🇿',
    footer_location: 'سوق أهراس، الجزائر',
    search_results: 'نتائج البحث عن "{search}"',
    searching: 'جاري البحث...',
    no_products_found: 'لم يتم العثور على منتجات تطابق بحثك.',
    reviews_count: '{count} مراجعات',
    price: 'السعر',
    mrp: 'سعر التجزئة',
    save_percentage: 'وفر {percentage}% الآن',
    quantity: 'الكمية',
    add_to_cart: 'أضف إلى السلة',
    view_cart: 'عرض السلة',
    free_shipping: 'شحن مجاني عالمياً',
    secured_payment: 'دفع آمن 100%',
    trusted_brands: 'موثوق من أفضل العلامات التجارية',
    products: 'المنتجات',
    artisan: 'حرفي',
    description: 'الوصف',
    reviews: 'المراجعات',
    loading_reviews: 'جاري تحميل المراجعات...',
    no_reviews: 'لا توجد مراجعات لهذا المنتج بعد.',
    product_by: 'منتج بواسطة {name}',
    view_store: 'عرض المتجر',
    my_cart: 'سلة المشتريات',
    items_in_cart: 'منتجات في سلتك',
    add_more: 'أضف المزيد',
    product: 'المنتج',
    total_price: 'السعر الإجمالي',
    remove: 'إزالة',
    empty_cart: 'سلة المشتريات فارغة',
    payment_summary: 'ملخص الدفع',
    payment_method: 'طريقة الدفع',
    chargily: 'Chargily (ذهبية/CIB)',
    address: 'العنوان',
    select_address: 'اختر العنوان',
    add_address: 'أضف عنوان',
    subtotal: 'المجموع الفرعي:',
    shipping: 'الشحن:',
    free: 'مجاني',
    total: 'المجموع:',
    place_order: 'إتمام الطلب',
    select_shipping_address_error: 'يرجى تحديد عنوان شحن',
    no_active_cart_error: 'لم يتم العثور على سلة نشطة',
    conversations: 'المحادثات',
    all_conversations: 'جميع المحادثات',
    no_conversations: 'لا توجد محادثات بعد',
    start_conv_hint: 'ابدأ محادثة من صفحة أي بائع',
    start_conv: 'ابدأ المحادثة',
    choose_conv: 'اختر محادثة للبدء',
    online: 'متصل',
    type_message: 'اكتب رسالة...',
  },
  en: {
    profile: 'Profile',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    logout: 'Logout',
    edit: 'Edit',
    name: 'Name',
    bio: 'Bio',
    location: 'Location',
    save: 'Save Changes',
    dark: 'Dark',
    light: 'Light',
    arabic: 'Arabic',
    english: 'English',
    my_account: 'My Account',
    home: 'Home',
    shop: 'Shop',
    about: 'About',
    contact: 'Contact',
    become_artisan: 'Become an Artisan',
    store_setup: 'Store Setup',
    store_name: 'Store Name',
    store_description: 'Store Description',
    submit: 'Submit',
    privacy_policy: 'Privacy Policy',
    login: 'Login',
    all_products: 'All Products',
    latest_products: 'Latest Products',
    best_selling: 'Best Selling',
    specifications: 'Our Specifications',
    newsletter_title: 'Join Our Newsletter',
    newsletter_desc: 'Get the latest updates and exclusive offers delivered straight to your inbox.',
    get_updates: 'Get Updates',
    view_more: 'View More',
    showing_products: 'Showing {count} of {total} products',
    wishlist: 'Wishlist',
    search_placeholder: 'Search for products...',
    search_btn: 'Search',
    my_orders: 'My Orders',
    hero_badge: 'NEW',
    hero_badge_text: 'Support local artisans - every piece is unique',
    hero_title: 'Authentic handmade products. With an Algerian touch.',
    hero_desc: 'Discover the wonders of Algerian handicrafts - from pottery to textiles, every product tells the story of our ancient heritage.',
    price_starts: 'Prices start from',
    explore_products: 'Explore Products',
    traditional_crafts: 'Traditional Crafts',
    natural_products: 'Natural Products',
    discover_more: 'Discover More',
    browse_now: 'Browse Now',
    enter_email: 'Enter your email address',
    spec_shipping_title: 'Free Shipping',
    spec_shipping_desc: 'Fast and free delivery for all orders nationwide',
    spec_returns_title: 'Easy 7-Day Returns',
    spec_returns_desc: 'Changed your mind? No problem. You can return the product within 7 days',
    spec_support_title: '24/7 Support',
    spec_support_desc: 'We are here to help you anytime with professional customer service',
    specifications_desc: 'We offer top-tier service and convenience to ensure your shopping experience is smooth, secure and completely hassle-free.',
    categories_title: 'Categories',
    useful_links: 'Useful Links',
    contact_us: 'Contact Us',
    footer_desc: 'Manuva - Your primary platform to discover authentic Algerian artisanal products. From pottery to textiles, every piece tells a story of our heritage and supports our local artisans.',
    copyright: 'Copyright 2026 © Manuva. All rights reserved.',
    made_with_love: 'Made with love in Algeria 🇩🇿',
    footer_location: 'Souk Ahras, Algeria',
    search_results: 'Search results for "{search}"',
    searching: 'Searching...',
    no_products_found: 'No products found matching your search.',
    reviews_count: '{count} Reviews',
    price: 'Price',
    mrp: 'MRP',
    save_percentage: 'Save {percentage}% right now',
    quantity: 'Quantity',
    add_to_cart: 'Add to Cart',
    view_cart: 'View Cart',
    free_shipping: 'Free shipping worldwide',
    secured_payment: '100% Secured Payment',
    trusted_brands: 'Trusted by top brands',
    products: 'Products',
    artisan: 'Artisan',
    description: 'Description',
    reviews: 'Reviews',
    loading_reviews: 'Loading reviews...',
    no_reviews: 'No reviews yet for this product.',
    product_by: 'Product by {name}',
    view_store: 'view store',
    my_cart: 'My Cart',
    items_in_cart: 'items in your cart',
    add_more: 'Add more',
    product: 'Product',
    total_price: 'Total Price',
    remove: 'Remove',
    empty_cart: 'Your cart is empty',
    payment_summary: 'Payment Summary',
    payment_method: 'Payment Method',
    chargily: 'Chargily (Edahabia/CIB)',
    address: 'Address',
    select_address: 'Select Address',
    add_address: 'Add Address',
    subtotal: 'Subtotal:',
    shipping: 'Shipping:',
    free: 'Free',
    total: 'Total:',
    place_order: 'Place Order',
    select_shipping_address_error: 'Please select a shipping address',
    no_active_cart_error: 'No active cart found',
    conversations: 'Conversations',
    all_conversations: 'All conversations',
    no_conversations: 'No conversations yet',
    start_conv_hint: "Start a conversation from any seller's page",
    start_conv: 'Start conversation',
    choose_conv: 'Choose a conversation to start',
    online: 'Online',
    type_message: 'Type a message...',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ar');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') || 'ar';
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
    document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key, data = {}) => {
    let text = translations[language][key] || key;
    Object.keys(data).forEach(k => {
      text = text.replace(`{${k}}`, data[k]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
